services:
  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      DATABASE_USER: ${DATABASE_USER:-dev_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-dev_pass}
      DATABASE_NAME: ${DATABASE_NAME:-dev_db}

    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - db_data:/var/lib/postgresql/data
    ports:
      - "8003:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myflix-network
    restart: unless-stopped